import type { EntityKind } from '@/lib/types/entityTypes';
import type { RelationshipDirection, RelationshipCardinality } from '../../types';

export interface RelationshipPreset {
  id: string;
  name: string;
  description: string;
  category: 'character' | 'location' | 'narrative' | 'faction';
  source_entity_kind: EntityKind;
  target_entity_kind: EntityKind;
  relationship_name: string;
  display_label: string;
  direction: RelationshipDirection;
  cardinality: RelationshipCardinality;
  inverse_label?: string;
}

export const RELATIONSHIP_PRESETS: RelationshipPreset[] = [
  {
    id: 'char_member_faction',
    name: 'Member Of',
    description: 'A character belongs to or is a member of a faction, guild, or organization.',
    category: 'character',
    source_entity_kind: 'CHARACTER',
    target_entity_kind: 'FACTION',
    relationship_name: 'character_member_of_faction',
    display_label: 'member of',
    direction: 'directed',
    cardinality: 'many_to_many',
    inverse_label: 'has member',
  },
  {
    id: 'char_knows_char',
    name: 'Knows',
    description: 'Two characters know each other or have met.',
    category: 'character',
    source_entity_kind: 'CHARACTER',
    target_entity_kind: 'CHARACTER',
    relationship_name: 'character_knows_character',
    display_label: 'knows',
    direction: 'bidirectional',
    cardinality: 'many_to_many',
  },
  {
    id: 'char_owns_item',
    name: 'Owns',
    description: 'A character possesses or owns an item.',
    category: 'character',
    source_entity_kind: 'CHARACTER',
    target_entity_kind: 'ITEM',
    relationship_name: 'character_owns_item',
    display_label: 'owns',
    direction: 'directed',
    cardinality: 'one_to_many',
    inverse_label: 'owned by',
  },
  {
    id: 'char_related_char',
    name: 'Related To',
    description: 'Two characters are related by blood or marriage.',
    category: 'character',
    source_entity_kind: 'CHARACTER',
    target_entity_kind: 'CHARACTER',
    relationship_name: 'character_related_to_character',
    display_label: 'related to',
    direction: 'bidirectional',
    cardinality: 'many_to_many',
  },
  {
    id: 'char_rivals_char',
    name: 'Rivals',
    description: 'Two characters are rivals or enemies.',
    category: 'character',
    source_entity_kind: 'CHARACTER',
    target_entity_kind: 'CHARACTER',
    relationship_name: 'character_rivals_character',
    display_label: 'rivals with',
    direction: 'bidirectional',
    cardinality: 'many_to_many',
  },
  {
    id: 'loc_contains_loc',
    name: 'Contains',
    description: 'A location contains another location (e.g., city contains buildings).',
    category: 'location',
    source_entity_kind: 'LOCATION',
    target_entity_kind: 'LOCATION',
    relationship_name: 'location_contains_location',
    display_label: 'contains',
    direction: 'directed',
    cardinality: 'one_to_many',
    inverse_label: 'located in',
  },
  {
    id: 'char_located_at',
    name: 'Located At',
    description: 'A character is currently located at or resides in a location.',
    category: 'location',
    source_entity_kind: 'CHARACTER',
    target_entity_kind: 'LOCATION',
    relationship_name: 'character_located_at',
    display_label: 'located at',
    direction: 'directed',
    cardinality: 'many_to_one',
    inverse_label: 'has resident',
  },
  {
    id: 'event_occurs_at',
    name: 'Occurs At',
    description: 'An event takes place at a specific location.',
    category: 'location',
    source_entity_kind: 'EVENT',
    target_entity_kind: 'LOCATION',
    relationship_name: 'event_occurs_at',
    display_label: 'occurs at',
    direction: 'directed',
    cardinality: 'many_to_one',
    inverse_label: 'site of',
  },
  {
    id: 'loc_connected_to',
    name: 'Connected To',
    description: 'Two locations are connected by a path, road, or portal.',
    category: 'location',
    source_entity_kind: 'LOCATION',
    target_entity_kind: 'LOCATION',
    relationship_name: 'location_connected_to',
    display_label: 'connected to',
    direction: 'bidirectional',
    cardinality: 'many_to_many',
  },
  {
    id: 'scene_part_of_chapter',
    name: 'Part Of Chapter',
    description: 'A scene is part of a chapter in the narrative.',
    category: 'narrative',
    source_entity_kind: 'SCENE',
    target_entity_kind: 'CHAPTER',
    relationship_name: 'scene_part_of_chapter',
    display_label: 'part of',
    direction: 'directed',
    cardinality: 'many_to_one',
    inverse_label: 'contains scene',
  },
  {
    id: 'event_triggers_event',
    name: 'Triggers',
    description: 'One event causes or triggers another event.',
    category: 'narrative',
    source_entity_kind: 'EVENT',
    target_entity_kind: 'EVENT',
    relationship_name: 'event_triggers_event',
    display_label: 'triggers',
    direction: 'directed',
    cardinality: 'one_to_many',
    inverse_label: 'triggered by',
  },
  {
    id: 'arc_contains_act',
    name: 'Contains Act',
    description: 'A story arc contains one or more acts.',
    category: 'narrative',
    source_entity_kind: 'ARC',
    target_entity_kind: 'ACT',
    relationship_name: 'arc_contains_act',
    display_label: 'contains',
    direction: 'directed',
    cardinality: 'one_to_many',
    inverse_label: 'belongs to',
  },
  {
    id: 'chapter_contains_beat',
    name: 'Contains Beat',
    description: 'A chapter contains story beats.',
    category: 'narrative',
    source_entity_kind: 'CHAPTER',
    target_entity_kind: 'BEAT',
    relationship_name: 'chapter_contains_beat',
    display_label: 'contains',
    direction: 'directed',
    cardinality: 'one_to_many',
    inverse_label: 'in chapter',
  },
  {
    id: 'char_participates_event',
    name: 'Participates In',
    description: 'A character participates in or witnesses an event.',
    category: 'narrative',
    source_entity_kind: 'CHARACTER',
    target_entity_kind: 'EVENT',
    relationship_name: 'character_participates_event',
    display_label: 'participates in',
    direction: 'directed',
    cardinality: 'many_to_many',
    inverse_label: 'involves',
  },
  {
    id: 'faction_allied_with',
    name: 'Allied With',
    description: 'Two factions are allies or have a cooperative relationship.',
    category: 'faction',
    source_entity_kind: 'FACTION',
    target_entity_kind: 'FACTION',
    relationship_name: 'faction_allied_with',
    display_label: 'allied with',
    direction: 'bidirectional',
    cardinality: 'many_to_many',
  },
  {
    id: 'faction_rivals',
    name: 'Rivals',
    description: 'Two factions are rivals, enemies, or in conflict.',
    category: 'faction',
    source_entity_kind: 'FACTION',
    target_entity_kind: 'FACTION',
    relationship_name: 'faction_rivals',
    display_label: 'rivals with',
    direction: 'bidirectional',
    cardinality: 'many_to_many',
  },
  {
    id: 'faction_controls_location',
    name: 'Controls',
    description: 'A faction controls, governs, or occupies a location.',
    category: 'faction',
    source_entity_kind: 'FACTION',
    target_entity_kind: 'LOCATION',
    relationship_name: 'faction_controls_location',
    display_label: 'controls',
    direction: 'directed',
    cardinality: 'one_to_many',
    inverse_label: 'controlled by',
  },
  {
    id: 'faction_subfaction',
    name: 'Has Subfaction',
    description: 'A faction has smaller factions or divisions within it.',
    category: 'faction',
    source_entity_kind: 'FACTION',
    target_entity_kind: 'FACTION',
    relationship_name: 'faction_has_subfaction',
    display_label: 'has subfaction',
    direction: 'directed',
    cardinality: 'one_to_many',
    inverse_label: 'subfaction of',
  },
];

export const PRESET_CATEGORIES = [
  { id: 'character', label: 'Character', color: '#8b5cf6' },
  { id: 'location', label: 'Location', color: '#3b82f6' },
  { id: 'narrative', label: 'Narrative', color: '#ec4899' },
  { id: 'faction', label: 'Faction', color: '#ef4444' },
] as const;

export type PresetCategory = typeof PRESET_CATEGORIES[number]['id'];
